# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  packages: !include_dir_named packages/

logger:
  default: info
  logs:
    hacs: debug

lovelace:
  mode: yaml
  resources:
    - type: module
      url: /hacsfiles/button-card/button-card.js
    - type: module
      url: /hacsfiles/lovelace-state-switch/state-switch.js
    - type: module
      url: http://127.0.0.1:5000/time-picker-card.js
  dashboards:
    lovelace-home:
      mode: yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: true
      filename: ui-lovelace.yaml
