title: Home
views:
  - title: Grid
    path: grid
    cards:
      - type: grid
        cards:
          - type: button
            icon: mdi:reload
            name: Theme
            tap_action:
              action: call-service
              service: frontend.reload_themes
          - type: custom:time-picker-card
            entity: input_datetime.test_date_time
            link_values: true
            hour_mode: 12
            hour_step: 2
            minute_step: 3
            layout:
              hour_mode: single
              name: inside
            hide:
              name: false
          - type: entities
            entities:
              - input_datetime.test_date_time
              - input_datetime.test_date_time
              - input_datetime.test_date_time
              - input_datetime.test_date_time
              - input_datetime.test_date_time
              - input_datetime.test_date_time


  - title: dev
    path: dev
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: "# 🕰 Time Picker Card dev"
          - type: entities
            entities:
              - input_datetime.test_date_time
          - type: horizontal-stack
            cards:
              - type: custom:time-picker-card
                entity: input_datetime.test_date_time
                name: Alarm time
                hour_mode: 24
                hour_step: 2
              - type: custom:time-picker-card
                entity: input_datetime.test_date_time
                hour_mode: 12
                layout:
                  hour_mode: single
                hide:
                  name: true

          - type: custom:time-picker-card
            entity: input_datetime.test_date_time
          - type: custom:time-picker-card
            entity: input_datetime.test_date_time
            hide:
              seconds: false

          - type: horizontal-stack
            cards:
              - type: custom:time-picker-card
                entity: input_datetime.test_date_time
                hour_mode: 12
                hide:
                  name: true
              - type: custom:time-picker-card
                entity: input_datetime.test_date_time
                link_values: true
                hour_mode: 12
                hour_step: 2
                minute_step: 3
                layout:
                  hour_mode: single
                hide:
                  name: false
