title: Home
views:
  - title: dev
    path: dev
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: "# 🕰 Time Picker Card dev"
          - type: entities
            entities:
              - input_datetime.test_date_time
          - type: horizontal-stack
            cards:
              - type: custom:time-picker-card
                entity: input_datetime.test_date_time
                name: Alarm time
                hour_mode: 24
                hour_step: 2
                tap_action:
                  action: call-service
                  service: logbook.log
                  service_data:
                    name: "Time picker card · Tap Action"
                    message: "Debug"
                double_tap_action:
                  action: call-service
                  service: logbook.log
                  service_data:
                    name: "Time picker card · Double Tap Action"
                    message: "Debug"
                hold_action:
                  action: call-service
                  service: logbook.log
                  service_data:
                    name: "Time picker card · Hold action"
                    message: "Debug"
              - type: custom:time-picker-card
                entity: input_datetime.test_date_time
                hour_mode: 12
                layout:
                  hour_mode: single
                hide:
                  name: true

          - type: custom:time-picker-card
            entity: input_datetime.test_date_time
          - type: custom:time-picker-card
            entity: input_datetime.test_date_time
            hide:
              seconds: false

          - type: horizontal-stack
            cards:
              - type: custom:time-picker-card
                entity: input_datetime.test_date_time
                hour_mode: 12
                hide:
                  name: true
              - type: custom:time-picker-card
                entity: input_datetime.test_date_time
                link_values: true
                hour_mode: 12
                hour_step: 2
                minute_step: 3
                layout:
                  hour_mode: single
                hide:
                  name: false

          - type: custom:time-picker-card
            entity: input_datetime.test_date
            link_values: true
            hour_mode: 12
            hour_step: 2
            minute_step: 3
            layout:
              hour_mode: single
            hide:
              name: false

  - title: embedded
    path: embedded
    cards:
      - type: vertical-stack
        cards:

          - type: entities
            entities:
              - input_datetime.test_date_time
              - type: custom:time-picker-card
                entity: input_datetime.test_date_time
                name: Alarm time
                hour_mode: 24
                hour_step: 2
                layout:
                  embedded: true
              - type: custom:time-picker-card
                entity: input_datetime.test_date_time
                hour_mode: 12
                layout:
                  hour_mode: single
                hide:
                  name: true
              - type: custom:time-picker-card
                entity: input_datetime.test_date_time
                hour_mode: 12
                layout:
                  hour_mode: single
